//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Celiii
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Список анкет.
    /// </summary>
    // *** Start programmer edit section *** (СписокАнкет CustomAttributes)

    // *** End programmer edit section *** (СписокАнкет CustomAttributes)
    [AutoAltered()]
    [Caption("Список анкет")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СписокАнкетE", new string[] {
            "Анкеты as \'Номер\'",
            "Анкеты.ГлавнПричин as \'Причина\'",
            "Анкеты.ОтносКатСотр as \'Категория сотрудника\'",
            "Анкеты.Коммент as \'Комментарий\'"})]
    [MasterViewDefineAttribute("СписокАнкетE", "Анкеты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    public class СписокАнкет : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Celiii.Анкеты fАнкеты;
        
        private IIS.Celiii.ПричинУвольн fПричинУвольн;
        
        // *** Start programmer edit section *** (СписокАнкет CustomMembers)

        // *** End programmer edit section *** (СписокАнкет CustomMembers)

        
        /// <summary>
        /// Список анкет.
        /// </summary>
        // *** Start programmer edit section *** (СписокАнкет.Анкеты CustomAttributes)

        // *** End programmer edit section *** (СписокАнкет.Анкеты CustomAttributes)
        [PropertyStorage(new string[] {
                "Анкеты"})]
        public virtual IIS.Celiii.Анкеты Анкеты
        {
            get
            {
                // *** Start programmer edit section *** (СписокАнкет.Анкеты Get start)

                // *** End programmer edit section *** (СписокАнкет.Анкеты Get start)
                IIS.Celiii.Анкеты result = this.fАнкеты;
                // *** Start programmer edit section *** (СписокАнкет.Анкеты Get end)

                // *** End programmer edit section *** (СписокАнкет.Анкеты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокАнкет.Анкеты Set start)

                // *** End programmer edit section *** (СписокАнкет.Анкеты Set start)
                this.fАнкеты = value;
                // *** Start programmer edit section *** (СписокАнкет.Анкеты Set end)

                // *** End programmer edit section *** (СписокАнкет.Анкеты Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Celiii.ПричинУвольн.
        /// </summary>
        // *** Start programmer edit section *** (СписокАнкет.ПричинУвольн CustomAttributes)

        // *** End programmer edit section *** (СписокАнкет.ПричинУвольн CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ПричинУвольн"})]
        public virtual IIS.Celiii.ПричинУвольн ПричинУвольн
        {
            get
            {
                // *** Start programmer edit section *** (СписокАнкет.ПричинУвольн Get start)

                // *** End programmer edit section *** (СписокАнкет.ПричинУвольн Get start)
                IIS.Celiii.ПричинУвольн result = this.fПричинУвольн;
                // *** Start programmer edit section *** (СписокАнкет.ПричинУвольн Get end)

                // *** End programmer edit section *** (СписокАнкет.ПричинУвольн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокАнкет.ПричинУвольн Set start)

                // *** End programmer edit section *** (СписокАнкет.ПричинУвольн Set start)
                this.fПричинУвольн = value;
                // *** Start programmer edit section *** (СписокАнкет.ПричинУвольн Set end)

                // *** End programmer edit section *** (СписокАнкет.ПричинУвольн Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СписокАнкетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СписокАнкетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СписокАнкетE", typeof(IIS.Celiii.СписокАнкет));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СписокАнкет.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСписокАнкет CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСписокАнкет CustomAttributes)
    public class DetailArrayOfСписокАнкет : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Celiii.DetailArrayOfСписокАнкет members)

        // *** End programmer edit section *** (IIS.Celiii.DetailArrayOfСписокАнкет members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СписокАнкет by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СписокАнкет.
        /// </summary>
        public DetailArrayOfСписокАнкет(IIS.Celiii.ПричинУвольн fПричинУвольн) : 
                base(typeof(СписокАнкет), ((ICSSoft.STORMNET.DataObject)(fПричинУвольн)))
        {
        }
        
        public IIS.Celiii.СписокАнкет this[int index]
        {
            get
            {
                return ((IIS.Celiii.СписокАнкет)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Celiii.СписокАнкет dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
